// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARV4XGxeUwdoqzuJ0OAeekYhZnpKjyh3A',
    appId: '1:156434575324:web:6218e40e6a7e0dd20ee919',
    messagingSenderId: '156434575324',
    projectId: 'dimpos-8b7e2',
    authDomain: 'dimpos-8b7e2.firebaseapp.com',
    storageBucket: 'dimpos-8b7e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKoMwkALVSWtxQKF0UiOFIVWjfcNEovaY',
    appId: '1:156434575324:android:2bb997b766968b470ee919',
    messagingSenderId: '156434575324',
    projectId: 'dimpos-8b7e2',
    storageBucket: 'dimpos-8b7e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3mUCOD6TnCSPhXyOGYtzmNtlTWytVV8A',
    appId: '1:156434575324:ios:c8139e3fcbd2c2360ee919',
    messagingSenderId: '156434575324',
    projectId: 'dimpos-8b7e2',
    storageBucket: 'dimpos-8b7e2.firebasestorage.app',
    iosBundleId: 'com.example.dimposStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3mUCOD6TnCSPhXyOGYtzmNtlTWytVV8A',
    appId: '1:156434575324:ios:c8139e3fcbd2c2360ee919',
    messagingSenderId: '156434575324',
    projectId: 'dimpos-8b7e2',
    storageBucket: 'dimpos-8b7e2.firebasestorage.app',
    iosBundleId: 'com.example.dimposStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARV4XGxeUwdoqzuJ0OAeekYhZnpKjyh3A',
    appId: '1:156434575324:web:98fe9e56c4699aff0ee919',
    messagingSenderId: '156434575324',
    projectId: 'dimpos-8b7e2',
    authDomain: 'dimpos-8b7e2.firebaseapp.com',
    storageBucket: 'dimpos-8b7e2.firebasestorage.app',
  );
}
